# build a docker compost file with a mongo database, a python flask api, and a basic volume to hold files
version: '3.7'

services:
  mongodb:
    image: mongo:4.2.3
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  api:
    build: ./agent
    container_name: api
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    environment:
      - ATLAS_URI=mongodb://mongodb:27017
      - IOT_DB_NAME=iot
    depends_on:
     - mongodb

  webapp_server:
    build: ./backend
    container_name: webapp_server
    #restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017
      - NODE_ENV=development

  webapp_client:
    build: ./ui
    container_name: webapp_client
    #restart: always
    ports:
      - 4000:4000
    volumes:
      - ./data:/data
    environment:
      - PORT=4000
      - REACT_APP_API_URL=http://localhost
      - HOST=webapp_client

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - webapp_client
      - api