version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "thingscopemini"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-187rzn65rx22l"
s3_prefix = "thingscopemini"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
